# Generated by Django 5.0.7 on 2024-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('consumer_name', models.CharField(max_length=50)),
                ('consumer_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('brand_name', models.CharField(max_length=50)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
