# Generated by Django 5.0.7 on 2024-07-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_request_brand_name_alter_request_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('sub_cat_name', models.CharField(max_length=50, unique=True)),
                ('sub_cat_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.category')),
            ],
        ),
    ]
